apiVersion: v1
kind: ConfigMap
metadata:
  name: good-gateway-config
  namespace: kube-system
data:
  service-conf: |
    config:
      hostname: "good-gateway.npool.top"
      http_port: 50550
      grpc_port: 50551
      healthz_port: 50552
      prometheus_port: 50553
      appid: "89089012783789789719823798127398"
      serviceid: "49277608-4ebf-11ed-8300-b12398941ccf"
      logdir: "./"
      apolloAccessKey: "0147fb70b815403790e8634b899fac07"
