apiVersion: apps/v1
kind: Deployment
metadata:
  name: good-gateway
  namespace: kube-system
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: good-gateway
  template:
    metadata:
      labels:
        app: good-gateway
    spec:
      containers:
        - name: good-gateway
          image: uhub.service.ucloud.cn/entropypool/good-gateway:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: service-config
              mountPath: /etc/GoodGateway
          env:
            - name: ENV_ENVIRONMENT_TARGET
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.target
            - name: ENV_CONSUL_HOST
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_host
            - name: ENV_CONSUL_PORT
              valueFrom:
                configMapKeyRef:
                  name: system-environment
                  key: environment.consul_port
            - name: ENV_CLUSTER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
      volumes:
        - name: service-config
          configMap:
            name: good-gateway-config
            items:
              - key: service-conf
                path: GoodGateway.viper.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: good-gateway
  namespace: kube-system
spec:
  ports:
    - name: http
      port: 50550
      targetPort: 50550
    - name: grpc
      port: 50551
      targetPort: 50551
    - name: healthz
      port: 50552
      targetPort: 50552
    - name: prometheus
      port: 50553
      targetPort: 50553
  selector:
    app: good-gateway
