apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: good-gateway-traefik-app-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: good-gateway-traefik-app
    k8s.kuboard.cn/workload: good-gateway-traefik-app
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-oplog@kubernetescrd,
      kube-system-strip-good-gateway-prefix@kubernetescrd,
      kube-system-http-redirect-https@kubernetescrd,
      kube-system-common-headers@kubernetescrd,
      kube-system-headers-appid-to-body@kubernetescrd,
      kube-system-headers-userid-to-body@kubernetescrd,
      kube-system-headers-app-login-token-to-body@kubernetescrd,
      kube-system-app-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: /api/good/v1/version
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/appgoods
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/appgood
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/promotions
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/recommends
            backend:
              serviceName: good-gateway
              servicePort: 50550
    - host: api.procyon.vip
      http: *http_rules
    - host: api.xpool.top
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
    - host: api.development.npool.top
      http: *http_rules
    - host: api.procyon.xpool.top
      http: *http_rules
    - host: api.jh-testing.npool.top
      http: *http_rules
    - host: api.japan-procyon-production.npool.top
      http: *http_rules
    - host: api.lpsecretbase.com
      http: *http_rules
    - host: api.hk-cryptomore-production.npool.top
      http: *http_rules
    - host: api.cryptomore.io
      http: *http_rules

---

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: good-gateway-traefik-app-user-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: good-gateway-traefik-app-user
    k8s.kuboard.cn/workload: good-gateway-traefik-app-user
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-oplog@kubernetescrd,
      kube-system-strip-good-gateway-prefix@kubernetescrd,
      kube-system-http-redirect-https@kubernetescrd,
      kube-system-common-headers@kubernetescrd,
      kube-system-headers-appid-to-body@kubernetescrd,
      kube-system-headers-userid-to-body@kubernetescrd,
      kube-system-headers-app-login-token-to-body@kubernetescrd,
      kube-system-app-user-role-rbac-auth@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: /api/good/v1/create/appgood
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/n/appgoods
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/update/appgood
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/update/n/appgood
            backend:
              serviceName: good-gateway
              servicePort: 50550

          - path: /api/good/v1/create/deviceinfo
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/update/deviceinfo
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/deviceinfo
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/deviceinfos
            backend:
              serviceName: good-gateway
              servicePort: 50550

          - path: /api/good/v1/create/good
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/good
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/update/good
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/goods
            backend:
              serviceName: good-gateway
              servicePort: 50550

          - path: /api/good/v1/create/subgood
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/create/app/subgood
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/update/subgood
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/update/app/subgood
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/subgoods
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/app/subgoods
            backend:
              serviceName: good-gateway
              servicePort: 50550

          - path: /api/good/v1/create/vendorlocation
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/update/vendorlocation
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/vendorlocation
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/vendorlocations
            backend:
              serviceName: good-gateway
              servicePort: 50550

          - path: /api/good/v1/create/vendorbrand
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/update/vendorbrand
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/delete/vendorbrand
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/vendorbrand
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/vendorbrands
            backend:
              serviceName: good-gateway
              servicePort: 50550

          - path: /api/good/v1/create/defaultgood
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/create/n/defaultgood
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/defaultgoods
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/n/defaultgoods
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/delete/defaultgood
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/update/defaultgood
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/update/n/defaultgood
            backend:
              serviceName: good-gateway
              servicePort: 50550

          - path: /api/good/v1/create/topmost
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/create/n/topmost
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/topmosts
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/n/topmosts
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/delete/topmost
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/update/topmost
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/update/n/topmost
            backend:
              serviceName: good-gateway
              servicePort: 50550

          - path: /api/good/v1/create/topmostgood
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/create/n/topmostgood
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/topmostgoods
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/get/n/topmostgoods
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/delete/topmostgood
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/update/topmostgood
            backend:
              serviceName: good-gateway
              servicePort: 50550
          - path: /api/good/v1/update/n/topmostgood
            backend:
              serviceName: good-gateway
              servicePort: 50550
    - host: api.procyon.vip
      http: *http_rules
    - host: api.xpool.top
      http: *http_rules
    - host: api.ohhash.com
      http: *http_rules
    - host: api.development.npool.top
      http: *http_rules
    - host: api.procyon.xpool.top
      http: *http_rules
    - host: api.jh-testing.npool.top
      http: *http_rules
    - host: api.japan-procyon-production.npool.top
      http: *http_rules
    - host: api.lpsecretbase.com
      http: *http_rules
    - host: api.hk-cryptomore-production.npool.top
      http: *http_rules
    - host: api.cryptomore.io
      http: *http_rules
